config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  get 'impressum', to: 'dashboard#impressum'
  get 'privacy', to: 'dashboard#privacy'
  get 'about', to: 'dashboard#about'
  get 'faq', to: 'dashboard#faq'

  resources :users, only: [] do
    member do
      get :confirm_email
      get :manage_account
    end
  end

  resources :consumers, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :providers, only: [:index, :new, :create, :show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consumer.rb
class Consumer < User
  
end

app/models/dashboard.rb
class Dashboard
  def initialize(region: nil)
    # TODO pre filter by region (detected via IP Address)
  end

  def latest_consumers
    @latest_consumers ||= Consumer.confirmed.last(10)
  end

  def latest_providers
    @latest_providers ||= Provider.confirmed.last(10)
  end

  def consumers_count
    @consumers_count ||= Consumer.confirmed.count
  end

  def providers_count
    @providers_count ||= Provider.confirmed.count
  end
end

app/models/provider.rb
class Provider < User
  
end

app/models/user.rb
class User < ApplicationRecord
  before_create -> { self.confirmation_token = SecureRandom.urlsafe_base64.to_s }
  after_create -> { UserMailer.with(user: self).confirmation_email.deliver_later }, if: -> { !self.confirmed? }

  scope :search, ->(search_term) { search_term.present? ? where("name ILIKE :wc OR postal_code LIKE :pf OR city LIKE :wc", wc: "%#{search_term}%", pf: "#{search_term}%") : all }
  scope :confirmed, -> { where("confirmed_at IS NOT NULL") }

  validates :name, presence: true
  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :postal_code, numericality: true
  validates :city, presence: true
  validates :privacy, acceptance: true, allow_nil: false, on: :create

  def try_confirm(given_token)
    if matches_token?(given_token)
      confirm
    else
      false
    end
  end

  def matches_token?(given_token)
    given_token = given_token || ""
    expected_token = self.confirmation_token || ""

    ActiveSupport::SecurityUtils.secure_compare(given_token, expected_token)
  end

  def confirmed?
    self.confirmed_at.present?
  end

  def confirm
    return true if self.confirmed?
    
    self.confirmed_at = Time.now
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
end

app/controllers/concerns/authentication.rb
require 'active_support/concern'

module Authentication
  extend ActiveSupport::Concern

  # Copied from https://github.com/wardencommunity/rails_warden/blob/master/lib/rails_warden/authentication.rb
  # as include does not work somehow

  def warden
    request.env['warden']
  end

  # Proxy to the authenticated? method on warden
  # :api: public
  def authenticated?(*args)
    warden.authenticated?(*args)
  end

  # Access the currently logged in user
  # :api: public
  def current_user(*args)
    warden.user(*args)
  end

  def authorize!(record)
    unless record == current_user
      #redirect to show
      redirect_to record, alert: t('messages.user.not_authorized')
    end
  end

  def login!(user, scope: :default)
    warden.set_user(user, scope: scope)
  end

  # Logout the current user
  # :api: public
  def logout!(scope: nil)
    if scope
      warden.logout(scope)
      warden.clear_strategies_cache!(scope: scope)
    else
      warden.logout
      warden.clear_strategies_cache!
    end
  end

  # Proxy to the authenticate method on warden
  # :api: public
  def authenticate(*args)
    warden.authenticate(*args)
  end

  # Proxy to the authenticate method on warden
  # :api: public
  def authenticate!(*args)
    defaults = {action: RailsWarden.unauthenticated_action}
    if args.last.is_a? Hash
      args[-1] = defaults.merge(args.last)
    else
      args << defaults
    end
    warden.authenticate!(*args)
  end
end

app/controllers/consumers_controller.rb
class ConsumersController < ApplicationController
  before_action :set_consumer, only: [:show, :edit, :update, :destroy]

  # GET /consumers
  # GET /consumers.json
  def index
    @consumers = Consumer.confirmed.search(params[:search])
  end

  # GET /consumers/1
  # GET /consumers/1.json
  def show
  end

  # GET /consumers/new
  def new
    @consumer = Consumer.new
  end

  # POST /consumers
  # POST /consumers.json
  def create
    @consumer = Consumer.new(consumer_params)

    if @consumer.save
      redirect_to @consumer, notice: t('messages.user.profile_created')
    else
      render :new
    end
  end

  # GET /changes/1/edit
  def edit
    authorize! @consumer
  end

  # PATCH/PUT /changes/1
  # PATCH/PUT /changes/1.json
  def update
    authorize! @consumer

    if @consumer.update(change_params)
      redirect_to @consumer, notice: t('messages.user.profile_updated')
    else
      render :edit
    end
  end

  # DELETE /consumers/1
  # DELETE /consumers/1.json
  def destroy
    authorize! @consumer

    @consumer.destroy

    redirect_to root_url, notice: t('messages.user.profile_deleted')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consumer
      @consumer = Consumer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def consumer_params
      params.require(:consumer).permit(:name, :description, :phone, :email, :street, :postal_code, :city, :privacy)
    end

    def change_params
      params.require(:consumer).permit(:name, :description, :phone, :street, :postal_code, :city)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @dashboard = Dashboard.new
  end

  def impressum
  end

  def privacy
  end

  def about
  end

  def faq
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.confirmed.search(params[:search])
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    if @provider.save
      redirect_to @provider, notice: t('messages.user.profile_created')
    else
      render :new
    end
  end

  # GET /changes/1/edit
  def edit
    authorize! @provider
  end

  # PATCH/PUT /changes/1
  # PATCH/PUT /changes/1.json
  def update
    authorize! @provider

    if @provider.update(change_params)
      redirect_to @provider, notice: t('messages.user.profile_updated')
    else
      render :edit
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    authorize! @provider

    @provider.destroy

    redirect_to providers_url, notice: t('messages.user.profile_deleted')
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def provider_params
      params.require(:provider).permit(:name, :description, :phone, :email, :street, :postal_code, :city, :privacy)
    end

    def change_params
      params.require(:provider).permit(:name, :description, :phone, :street, :postal_code, :city)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:confirm_email, :manage_account]

  def confirm_email
      if confirmed?
        login! @user

        redirect_to @user, notice: t('messages.user.confirmed')
      else
        redirect_to @user, alert: t('messages.user.not_confirmed')
      end
  end

  def manage_account
    if confirmed?
      login! @user

      redirect_to_edit_user @user
    else
      # just redirect to show page
      redirect_to @user
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def confirmed?
      @user.try_confirm(params[:confirmation_token])
    end

    def redirect_to_edit_user(user)
      redirect_to user.kind_of?(Provider) ? edit_provider_url(user) : edit_consumer_url(user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consumers_helper.rb
module ConsumersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/consumers/_form.html.haml
.c-form__container
  = form_for @consumer do |f|
    - if @consumer.errors.any?
      #error_explanation
        %h2 Leider sind Ihre Daten unvollständig:
        %ul
          - @consumer.errors.full_messages.each do |message|
            %li= message

    .c-form__row
      = f.label :name, class: "c-form__label"
      = f.text_field :name, class: "c-form__input"
    .c-form__row
      = f.label :description, class: "c-form__label"
      = f.text_area :description, class: "c-form__input", rows: 10
    .c-form__row
      = f.label :phone, class: "c-form__label"
      = f.text_field :phone, class: "c-form__input"
    .c-form__row
      = f.label :email, class: "c-form__label"
      = f.text_field :email, class: "c-form__input", disabled: @consumer.persisted?
    .c-form__row
      = f.label :street, class: "c-form__label"
      = f.text_field :street, class: "c-form__input"
    .c-form__row
      .o-layout
        .o-layout__item.u-1_3.u-mb-small
          = f.label :postal_code, class: "c-form__label"
          = f.text_field :postal_code, class: "c-form__input"
        .o-layout__item.u-2_3
          = f.label :city, class: "c-form__label"
          = f.text_field :city, class: "c-form__input"

    - if @consumer.new_record?
      .c-form__row.u-mt-small
        .c-form__checkbox
          = f.check_box :privacy, class: "c-form__checkbox__input"
          = f.label :privacy, class: "c-form__checkbox__label" do
            Ich habe die
            = link_to "Datenschutzbestimmungen", privacy_path, class: "u-link", target: "_blank"
            gelesen und akzeptiere diese
    .c-form__actions
      = f.submit class: "c-button"

app/views/consumers/edit.html.haml
.c-form.c-form--consumer
  .c-form__color
    .u-intro
      %h1.u-title.with-spacing Profil bearbeiten
    .u-mt-large
      .u-mb-small= link_to t('views.back'), consumers_path, class: "u-link"
      = link_to 'Profil löschen', @consumer, method: :delete, data: { confirm: 'Sind sie sicher? Diese Aktion kann nicht rückgängig gemacht werden!' }, class: "u-link"

 
  .c-form__wrapper
    = render 'form'

app/views/consumers/index.html.haml
.o-site.o-site--spacing.u-bg-consumer.u-pb-huge
  .o-wrapper.o-wrapper--limit
    .c-listing__header
      .c-listing__title
        %h1.u-title
          %strong= @consumers.count
          - if params[:search]
            = "Treffer für »#{params[:search]}«"
          - else
          suchen Mundschutze
      .c-listing__action
        = link_to "Als Anbieter registrieren", new_consumer_url, class: "u-link"
    .c-listing
      %form{ method: 'get' }
        %input.c-listing__search{ value: params[:search], name: 'search', placeholder: "Anbieter durchsuchen", type: "text", required: true }
        .c-listing__search__actions
          - if params[:search]
            .c-listing__search__reset
              = link_to "Suche zurücksetzen", consumers_path, class: "u-link"
          %input.c-button{ type: "submit", value: "Suchen" }
      .c-listing-group
        - @consumers.each do |consumer|
          = link_to consumer_path(consumer), class: 'c-listing__item' do
            .c-listing__item__name= consumer.name
            .c-listing__item__city= "#{consumer.postal_code} #{consumer.city}"

app/views/consumers/new.html.haml
.c-form.c-form--consumer
  .c-form__color
    .u-intro
      %h1.u-title.with-spacing Du benötigst sterile Mundschutze?
      %p.u-text-font-muted.u-mb-tiny
        Bitte gib uns einige Details über dich und deine Praxis. So können Praxen in deiner Nähe dich finden und dich kontaktieren, wenn sie dich unterstützen können. Auf der
        = link_to "Startseite", root_path, class: "u-link"
        findest du eine durchsuchbare Übersicht über Praxen, die Mundschutze übrigen haben oder diese sterilisieren können und kannst direkt Kontakt zu diesen aufnehmen.
      %p.u-text-font-muted.u-mb-tiny
        Wenn deine Praxis Mundschutze übrig hat oder bei der Sterilisation helfen kann, kannst du dich in unsere
        = link_to "andere Liste", new_provider_url, class: "u-link"
        eintrage.
      %p.u-text-font-muted.u-mb-tiny
        Lasst uns gemeinsam Ärzten helfen!
  .c-form__wrapper
    = render 'form'

app/views/dashboard/about.html.haml
.o-site.o-site--spacing
  .o-wrapper.o-wrapper--limit.u-rich-text
    .u-mb-huge
      %h1.u-title.with-spacing.u-underline Gemeinsam stark gegen Corona
      %p Aktuell leiden viele Hausarztpraxen unter einem massiven Mangel an Hygieneprodukten – allen voran fehlt es an Mundschutz-Artikeln.
      %p Auf der anderen Seite gibt es viele Zahnarztpraxen mit ungenutzten Vorräten an Mundschutzen. Zudem haben Zahnärzte häufig die Möglichkeit Hygieneprodukte maschinell aufzubereiten und für die Wiederverwendung steril zu machen,
      %p
        %strong Wir möchten helfen, indem wir beide Seiten schnell und effektiv zusammenbringen.

  .o-wrapper.o-wrapper--limit.u-rich-text
    .u-mb-huge
      %h1.u-title.with-spacing.u-underline Wie funktioniert das?
      %p Praxen, die unterstützen können, stellen eingeschweißte und sterile Mundschutze in Zehner-Paketen an Arztpraxen in der Umgebung bereit.
      %p Nach der Nutzung werden die Mundschutze zurückgebracht und erneut aufgearbeitet und sterilisiert.
      %p
        %strong Damit wollen wir gemeinsam Ärzten im Kampf gegen das Virus helfen.
    .u-mt-large.u-mb-default
      %h1.u-title.with-spacing.u-underline Wer kann mitmachen?
      %p Wir möchten Zahnärzte, die unterstützen können einfach mit Praxen in Verbindung bringen, die Hilfe benötigen. Hierzu haben wir zwei Listen, in die Praxen sich eintragen können.


  .o-wrapper.u-mt-large.u-mb-large
    .o-layout
      .o-layout__item.u-1_2.u-mb-large
        .o-box.u-bg-provider.u-rich-text
          .u-intro
            %h2.u-subtitle.with-spacing Liste 1 – Ich kann unterstützen
          %ul.u-mb-large
            %li Ich habe Mundschutz-Artikel übrig, die ich kostenfrei abgeben kann
            %li Ich kann helfen verwendete Artikel aufzuarbeiten und steril zu machen
          = link_to "Als Anbieter eintragen", new_provider_url, class: "c-button"

      .o-layout__item.u-1_2.u-mb-large
        .o-box.u-bg-consumer.u-rich-text
          .u-intro
            %h2.u-subtitle.with-spacing Liste 2 – Ich benötige Unterstützung
          %ul.u-mb-large
            %li Ich benötige Mundschutz-Artikel
            %li Ich kann benutzte Artikel zur Aufarbeitung abgeben
          = link_to "Als Verbraucher eintragen", new_consumer_url, class: "c-button"

  .o-wrapper.o-wrapper--limit.u-rich-text.u-mb-huge
    .u-mb-default
      %h1.u-title.with-spacing.u-underline Du hast Fragen oder Feedback?
      %p
        Wir freuen uns über Fragen, Feedback und Anmerkungen zu unserem Projekt.
      %p
        Antworten zu häufig gestellen Fragen findest du in unseren 
        = link_to "FAQs", faq_path, class: "u-link"
        oder du erreichst uns auch per E-Mail unter
        = link_to t('general.email'), "mailto: #{t('general.email')}", class: "u-link"

  .o-wrapper.o-wrapper--limit.u-rich-text
    .u-mb-default
      %h1.u-title.with-spacing.u-underline Wer steckt hinter dem Projekt?
      %p
        Angefangen hat das Projekt mit einer Aktion von
        = link_to "Dr. Christian Leonhardt aus Augsburg.", "https://www.zahnaerzte-am-perlach.de/", target: "_blank", class: "u-link"
        Nachdem er von befreundeten Hausärzten vom Mangel an Hygieneartikeln erfahren hat, begann er überschüssige Mundschutze zu verschenken und gebrauchte Masken wieder aufzuarbeiten.
      %p
        Um dieses Angebot zu erweitern, und Anbieter als auch Verbraucher schnell miteinander zu verbinden, entstand dann diese Plattform, welche mit schneller Unterstützung von
        = link_to "bitside.de", "https://www.bitside.de", target: "_blank", class: "u-link"
        und
        = link_to "und-pohlen.de", "https://www.und-pohlen.de", target: "_blank", class: "u-link"
        in die Tat umgesetzt wurde.
    %figure.u-mb-large
      .o-crop= image_tag "dr_leonhardt.jpg"

app/views/dashboard/index.html.haml
.o-site
  .o-wrapper.u-mb-large
    .u-intro
      %h1.u-subtitle Gemeinsam stark gegen Corona
      %p.u-mb-tiny Wir unterstützen Haus- und Allgemeinärzte mit Mundschutzen. Wir haben diese Plattform geschaffen um Ärzte/Zahnärzte mit anderen Ärzten zusammenzubringen, die Mundschutze abgeben oder sterilisieren können, bzw. Mundschutze benötigen.
    %ol.o-list-inline
      %li.o-list-inline__item.u-mr-default= link_to "Wie funktioniert das?", about_path, class: 'u-link'
      %li.o-list-inline__item.u-mr-default= link_to "Fragen oder Feedback?", faq_path, class: 'u-link'

  .c-split-view
    .c-split-view__item.c-split-view--visible.c-split-view__item--provider{ id: 'provider-list-body' }
      %header.c-split-view__item__header{ data: { id: 'provider-list-body' } }
        %h1
          %strong.c-split-view__item__count= @dashboard.providers_count
          bieten Mundschutze
        .c-split-view__item__action= link_to('Als Anbieter registrieren', new_provider_url, class: 'u-link')
      .c-split-view__item__body
        .c-listing
          %input.c-listing__search{ id: "provider-search", placeholder: "Anbieter durchsuchen", type: "text" }
          .c-split-view__item__mobile-action= link_to('Als Anbieter registrieren', new_provider_url, class: 'u-link')
          .c-listing-group{ id: "provider-list" }
            - @dashboard.latest_providers.each do |provider|
              = link_to provider_path(provider), class: 'c-listing__item' do
                .c-listing__item__name= provider.name
                .c-listing__item__city= "#{provider.postal_code} #{provider.city}"
          - if @dashboard.providers_count > 10
            .c-listing__more= link_to "Alle Anbieter sehen", providers_path, class: "u-link"

    .c-split-view__item.c-split-view__item--consumer{ id: 'consumer-list-body' }
      %header.c-split-view__item__header{ data: { id: 'consumer-list-body' } }
        %h1
          %strong.c-split-view__item__count= @dashboard.consumers_count
          suchen Mundschutze
        .c-split-view__item__action= link_to('Als Verbraucher registrieren', new_consumer_url, class: 'u-link')
      .c-split-view__item__body
        .c-listing
          %input.c-listing__search{ id: "consumer-search", placeholder: "Verbraucher durchsuchen", type: "text" }
          .c-split-view__item__mobile-action= link_to('Als Verbraucher registrieren', new_consumer_url, class: 'u-link')
          .c-listing-group{ id: "consumer-list" }
            - @dashboard.latest_consumers.each do |consumer|
              = link_to consumer_path(consumer), class: 'c-listing__item' do
                .c-listing__item__name= consumer.name
                .c-listing__item__city= "#{consumer.postal_code} #{consumer.city}"
          - if @dashboard.consumers_count > 10
            .c-listing__more= link_to "Alle Verbraucher sehen", consumers_path, class: "u-link"


:javascript
  (function() {
    function search(url, listId) {

      const headers = new Headers();
      headers.set('Content-Type', 'text/html');
      headers.set('Accept', 'text/html');
      const options = {
          method: 'GET',
          headers,
          mode: 'no-cors'
      };

      fetch(url, options)
      .then((response) => {
        return response.text();
      })
      .then((response) => {
        const list = document.getElementById(listId);
        const element = document.createElement('div');
        element.innerHTML = response;
        list.innerHTML = '';
        [...element.getElementsByClassName('c-listing-group')[0].children].forEach((child) => {
          list.appendChild(child);
        })
      });
    }

    const listHeaders = document.querySelectorAll('.c-split-view__item__header');
    listHeaders.forEach((el) => {
      el.addEventListener('click', (e) => {
        const id = el.getAttribute('data-id');
        const oldElements = document.querySelectorAll('.c-split-view__item');
        oldElements.forEach((oldEl) => {
          oldEl.classList.remove('c-split-view--visible');
        });
        document.getElementById(id).classList.toggle('c-split-view--visible');
      });
    });

    document.getElementById('provider-search').addEventListener('input', window.lodash.debounce((evt) => {
      const val = evt.target.value;
      search(`providers?search=${val}`, 'provider-list')
    }), 100);

    document.getElementById('consumer-search').addEventListener('input', window.lodash.debounce((evt) => {
      const val = evt.target.value;
      search(`consumers?search=${val}`, 'consumer-list')
    }), 100);
  })();

app/views/providers/_form.html.haml
.c-form__container
  = form_for @provider do |f|
    - if @provider.errors.any?
      #error_explanation
        %h2 Leider sind Ihre Daten unvollständig:
        %ul
          - @provider.errors.full_messages.each do |message|
            %li= message

    .c-form__row
      = f.label :name, class: "c-form__label"
      = f.text_field :name, class: "c-form__input"
    .c-form__row
      = f.label :description, class: "c-form__label"
      = f.text_area :description, class: "c-form__input", rows: 10
      %i.c-form__hint Gib hier bspw. an wann oder wie viele Masken du bereitstellen kannst.
    .c-form__row
      = f.label :phone, class: "c-form__label"
      = f.text_field :phone, class: "c-form__input"
    .c-form__row
      = f.label :email, class: "c-form__label"
      = f.text_field :email, class: "c-form__input", disabled: @provider.persisted?
    .c-form__row
      = f.label :street, class: "c-form__label"
      = f.text_field :street, class: "c-form__input"
    .c-form__row
      .o-layout
        .o-layout__item.u-1_3.u-mb-small
          = f.label :postal_code, class: "c-form__label"
          = f.text_field :postal_code, class: "c-form__input"
        .o-layout__item.u-2_3
          = f.label :city, class: "c-form__label"
          = f.text_field :city, class: "c-form__input"

    - if @provider.new_record?
      .c-form__row.u-mt-small
        .c-form__checkbox
          = f.check_box :privacy, class: "c-form__checkbox__input"
          = f.label :privacy, class: "c-form__checkbox__label" do
            Ich habe die
            = link_to "Datenschutzbestimmungen", privacy_path, class: "u-link", target: "_blank"
            gelesen und akzeptiere diese
    .c-form__actions
      = f.submit class: "c-button"

app/views/providers/edit.html.haml
.c-form.c-form--provider
  .c-form__color
    .u-intro
      %h1.u-title.with-spacing Profil bearbeiten
    .u-mt-large
      .u-mb-small= link_to t('views.back'), providers_path, class: "u-link"
      = link_to 'Profil löschen', @provider, method: :delete, data: { confirm: 'Sind sie sicher? Diese Aktion kann nicht rückgängig gemacht werden!' }, class: "u-link"

 
  .c-form__wrapper
    = render 'form'

app/views/providers/index.html.haml
.o-site.o-site--spacing.u-bg-provider.u-pb-huge
  .o-wrapper.o-wrapper--limit
    .c-listing__header
      .c-listing__title
        %h1.u-title
          %strong= @providers.count
          - if params[:search]
            = "Treffer für »#{params[:search]}«"
          - else
          bieten Mundschutze
      .c-listing__action
        = link_to "Als Anbieter registrieren", new_provider_url, class: "u-link"
    .c-listing
      %form{ method: 'get' }
        %input.c-listing__search{ value: params[:search], name: 'search', placeholder: "Anbieter durchsuchen", type: "text", required: true }
        .c-listing__search__actions
          - if params[:search]
            .c-listing__search__reset
              = link_to "Suche zurücksetzen", providers_path, class: "u-link"
          %input.c-button{ type: "submit", value: "Suchen" }
      .c-listing-group
        - @providers.each do |provider|
          = link_to provider_path(provider), class: 'c-listing__item' do
            .c-listing__item__name= provider.name
            .c-listing__item__city= "#{provider.postal_code} #{provider.city}"

app/views/providers/new.html.haml
.c-form.c-form--provider
  .c-form__color
    .u-intro
      %h1.u-title.with-spacing Vielen Dank, dass du Mundschutze teilst oder sterilisieren kannst.
      %p.u-text-font-muted.u-mb-tiny
        Bitte gib uns einige Details über dich und deine Praxis. So können Praxen in deiner Nähe dich finden und dich kontaktieren, wenn sie deine Unterstützung benötigen. Solltest du selbst Mundschutze benötigen, kannst du dich in
        = link_to "in unsere andere Liste", new_consumer_url, class: "u-link"
        eintragen.
      %p.u-text-font-muted Lasst uns gemeinsam Ärzten helfen!
 
  .c-form__wrapper
    = render 'form'

app/views/shared/_header.html.haml
.c-header
  = link_to "Mundschutztausch", root_path, class: "c-header__item is-title"
  .c-header__item.toggle.js-toggle
    %svg{:height => "20", :width => "20"}
      %path{:d => "M0,2 20,2"}
      %path{:d => "M0,10 20,10"}
      %path{:d => "M0,18 20,18"}


%nav.c-menu
  .c-header__item.toggle.c-menu__close.js-toggle
    %svg{:height => "20", :width => "20"}
      %line{:x1 => "0", :x2 => "20", :y1 => "20", :y2 => "0"}
      %line{:x1 => "0", :x2 => "20", :y1 => "0", :y2 => "20"}


  %ol.u-mb-huge.u-font-lg
    %li.u-mb-tiny= link_to "Als Anbieter mitmachen", new_provider_path, class: "c-menu__link"
    %li.u-mb-tiny= link_to "Als Verbraucher registrieren", new_consumer_path, class: "c-menu__link"
    %li.u-mb-tiny= link_to "Über das Projekt", about_path, class: "c-menu__link"
    %li.u-mb-tiny= link_to "FAQ", faq_path, class: "c-menu__link"

  %ol
    %li.u-mb-tiny= link_to "Impressum", impressum_path, class: "c-menu__link"
    %li.u-mb-tiny= link_to "Datenschutz", privacy_path, class: "c-menu__link"

:javascript
  (function() {
    const toggle = document.querySelectorAll('.js-toggle');
    toggle.forEach((el) => {
      el.addEventListener('click', (e) => {
        const menu = document.querySelector('.c-menu');
        menu.classList.toggle('is-visible');
      });
    });
  })();